name: CD

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: Production
    
    steps:
    - uses: actions/checkout@v3

    - name:  Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: 'subscription'
          template: ./.bicep/main.bicep
          region: 'West Europe'
